---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: magestack-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magestack
  template:
    metadata:
      labels:
        app: magestack
    spec:
      containers:
      - image: nginx:1.8-alpine
        name: magestack-nginx
        ports:
        - containerPort: 80
        volumeMounts:
          - name: config
            mountPath: /etc/nginx/conf.d/
      volumes:
        - name: config
          configMap:
            name: magestack-configmap
...
