version: '3.7'

services:
  elastic:
    build:
      context: .
      dockerfile: ./docker/services/elastic/Dockerfile
    image: ${DOCKER_PROJECT_NAME}_elastic
    container_name: ${DOCKER_PROJECT_NAME}_elastic
    working_dir: ${DOCKER_PROJECT_PATCH}
    networks:
      - net
    environment:
      - discovery.type=single-node
    ports:
      - '9200:9200'
      - '9300:9300'

  redis:
    build:
      context: .
      dockerfile: ./docker/services/redis/Dockerfile
    image: ${DOCKER_PROJECT_NAME}_redis
    container_name: ${DOCKER_PROJECT_NAME}_redis
    networks:
      - net
    ports:
      - '${DOCKER_REDIS_PORT:-6379}:6379'
    volumes:
      - ./docker/scripts/redis.sh:/scripts/redis.sh
    environment:
      - PASSWORD=${DOCKER_REDIS_PASSWORD}
    command: /scripts/redis.sh

  mysql:
    build:
      context: .
      dockerfile: ./docker/services/mysql/Dockerfile
    image: ${DOCKER_PROJECT_NAME}_mysql
    container_name: ${DOCKER_PROJECT_NAME}_mysql
    networks:
      - net
    ports:
      - '${DOCKER_MYSQL_PORT:-3306}:3306'
    volumes:
      - ./docker/services/mysql/conf/custom.cnf:/etc/mysql/custom.cnf
      - ./docker/services/mysql/var/backups/sql:/var/backups/sql
    environment:
      - MYSQL_DATABASE=${DOCKER_PROJECT_NAME}
      - MYSQL_ROOT_PASSWORD=${DOCKER_MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${DOCKER_MYSQL_USER}
      - MYSQL_PASSWORD=${DOCKER_MYSQL_PASSWORD}

  php:
    build:
      context: .
      dockerfile: ./docker/services/php/${DOCKER_PHP_VERSION}/Dockerfile
    image: ${DOCKER_PROJECT_NAME}_php
    container_name: ${DOCKER_PROJECT_NAME}_php
    working_dir: ${DOCKER_PROJECT_PATCH}
    networks:
      - net
    ports:
    - '9001:9001'
    volumes:
      - ${DOCKER_PROJECT_ROOT}:${DOCKER_PROJECT_PATCH}
      - ./docker/services/php/${DOCKER_PHP_VERSION}/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker/services/php/${DOCKER_PHP_VERSION}/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./docker/services/php/${DOCKER_PHP_VERSION}/conf.d/supervisord.ini:/etc/supervisor.d/supervisord.ini
      - ./docker/scripts/php.sh:/scripts/php.sh
    environment:
      - PROJECT_PATCH=${DOCKER_PROJECT_PATCH}
      - MYSQL_HOST=${DOCKER_PROJECT_NAME}_mysql
      - ELASTIC_HOST=${DOCKER_PROJECT_NAME}_elastic
    command: /scripts/php.sh

  nginx:
    build:
      context: .
      dockerfile: ./docker/services/nginx/Dockerfile
    image: ${DOCKER_PROJECT_NAME}_nginx
    container_name: ${DOCKER_PROJECT_NAME}_nginx
    working_dir: ${DOCKER_PROJECT_PATCH}
    networks:
      - net
    ports:
      - '${DOCKER_NGINX_PORT:-80}:80'
    volumes:
      - ${DOCKER_PROJECT_ROOT}:${DOCKER_PROJECT_PATCH}
      - ./docker/services/nginx/conf.d/${DOCKER_NGINX_CONFIG}:/etc/nginx/conf.d/docker.conf.template
      - ./docker/scripts/nginx.sh:/scripts/nginx.sh
    environment:
      - PROJECT_PATCH=${DOCKER_PROJECT_PATCH}
      - SERVER_NAME=${DOCKER_PROJECT_DOMAIN}
      - ROOT=${DOCKER_NGINX_ROOT}
      - CONFIG=${DOCKER_NGINX_CONFIG}
      - PHP_HOST=${DOCKER_PROJECT_NAME}_php
      - VIRTUAL_HOST=${DOCKER_PROJECT_DOMAIN}
      - MAGE_ROOT=${DOCKER_PROJECT_PATCH}
    command: /scripts/nginx.sh

networks:
  net:
    driver: bridge
